// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: RpcResult.proto
// Protobuf Java Version: 4.28.2

package com.skiff.protobuf.core;

public final class RpcResult {
    private RpcResult() {
    }

    static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                /* major= */ 4,
                /* minor= */ 28,
                /* patch= */ 2,
                /* suffix= */ "",
                RpcResult.class.getName());
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public interface ResultOrBuilder extends
            // @@protoc_insertion_point(interface_extends:Result)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string code = 1;</code>
         *
         * @return The code.
         */
        String getCode();

        /**
         * <code>string code = 1;</code>
         *
         * @return The bytes for code.
         */
        com.google.protobuf.ByteString
        getCodeBytes();

        /**
         * <code>bool success = 2;</code>
         *
         * @return The success.
         */
        boolean getSuccess();

        /**
         * <code>string message = 3;</code>
         *
         * @return The message.
         */
        String getMessage();

        /**
         * <code>string message = 3;</code>
         *
         * @return The bytes for message.
         */
        com.google.protobuf.ByteString
        getMessageBytes();

        /**
         * <code>bytes data = 4;</code>
         *
         * @return The data.
         */
        com.google.protobuf.ByteString getData();
    }

    /**
     * Protobuf type {@code Result}
     */
    public static final class Result extends
            com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:Result)
            ResultOrBuilder {
        private static final long serialVersionUID = 0L;

        static {
            com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
                    com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
                    /* major= */ 4,
                    /* minor= */ 28,
                    /* patch= */ 2,
                    /* suffix= */ "",
                    Result.class.getName());
        }

        // Use Result.newBuilder() to construct.
        private Result(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
        }

        private Result() {
            code_ = "";
            message_ = "";
            data_ = com.google.protobuf.ByteString.EMPTY;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return RpcResult.internal_static_Result_descriptor;
        }

        @Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return RpcResult.internal_static_Result_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            Result.class, Builder.class);
        }

        public static final int CODE_FIELD_NUMBER = 1;
        @SuppressWarnings("serial")
        private volatile Object code_ = "";

        /**
         * <code>string code = 1;</code>
         *
         * @return The code.
         */
        @Override
        public String getCode() {
            Object ref = code_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                code_ = s;
                return s;
            }
        }

        /**
         * <code>string code = 1;</code>
         *
         * @return The bytes for code.
         */
        @Override
        public com.google.protobuf.ByteString
        getCodeBytes() {
            Object ref = code_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                code_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int SUCCESS_FIELD_NUMBER = 2;
        private boolean success_ = false;

        /**
         * <code>bool success = 2;</code>
         *
         * @return The success.
         */
        @Override
        public boolean getSuccess() {
            return success_;
        }

        public static final int MESSAGE_FIELD_NUMBER = 3;
        @SuppressWarnings("serial")
        private volatile Object message_ = "";

        /**
         * <code>string message = 3;</code>
         *
         * @return The message.
         */
        @Override
        public String getMessage() {
            Object ref = message_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                message_ = s;
                return s;
            }
        }

        /**
         * <code>string message = 3;</code>
         *
         * @return The bytes for message.
         */
        @Override
        public com.google.protobuf.ByteString
        getMessageBytes() {
            Object ref = message_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                message_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int DATA_FIELD_NUMBER = 4;
        private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;

        /**
         * <code>bytes data = 4;</code>
         *
         * @return The data.
         */
        @Override
        public com.google.protobuf.ByteString getData() {
            return data_;
        }

        private byte memoizedIsInitialized = -1;

        @Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!com.google.protobuf.GeneratedMessage.isStringEmpty(code_)) {
                com.google.protobuf.GeneratedMessage.writeString(output, 1, code_);
            }
            if (success_ != false) {
                output.writeBool(2, success_);
            }
            if (!com.google.protobuf.GeneratedMessage.isStringEmpty(message_)) {
                com.google.protobuf.GeneratedMessage.writeString(output, 3, message_);
            }
            if (!data_.isEmpty()) {
                output.writeBytes(4, data_);
            }
            getUnknownFields().writeTo(output);
        }

        @Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!com.google.protobuf.GeneratedMessage.isStringEmpty(code_)) {
                size += com.google.protobuf.GeneratedMessage.computeStringSize(1, code_);
            }
            if (success_ != false) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(2, success_);
            }
            if (!com.google.protobuf.GeneratedMessage.isStringEmpty(message_)) {
                size += com.google.protobuf.GeneratedMessage.computeStringSize(3, message_);
            }
            if (!data_.isEmpty()) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(4, data_);
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof Result)) {
                return super.equals(obj);
            }
            Result other = (Result) obj;

            if (!getCode()
                    .equals(other.getCode())) return false;
            if (getSuccess()
                    != other.getSuccess()) return false;
            if (!getMessage()
                    .equals(other.getMessage())) return false;
            if (!getData()
                    .equals(other.getData())) return false;
            if (!getUnknownFields().equals(other.getUnknownFields())) return false;
            return true;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + CODE_FIELD_NUMBER;
            hash = (53 * hash) + getCode().hashCode();
            hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                    getSuccess());
            hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
            hash = (53 * hash) + getMessage().hashCode();
            hash = (37 * hash) + DATA_FIELD_NUMBER;
            hash = (53 * hash) + getData().hashCode();
            hash = (29 * hash) + getUnknownFields().hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public static Result parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Result parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Result parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Result parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Result parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static Result parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static Result parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input);
        }

        public static Result parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Result parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static Result parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static Result parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input);
        }

        public static Result parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessage
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        @Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(Result prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code Result}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:Result)
                ResultOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return RpcResult.internal_static_Result_descriptor;
            }

            @Override
            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return RpcResult.internal_static_Result_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                Result.class, Builder.class);
            }

            // Construct using com.skiff.protobuf.core.RpcResult.Result.newBuilder()
            private Builder() {

            }

            private Builder(
                    com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);

            }

            @Override
            public Builder clear() {
                super.clear();
                bitField0_ = 0;
                code_ = "";
                success_ = false;
                message_ = "";
                data_ = com.google.protobuf.ByteString.EMPTY;
                return this;
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return RpcResult.internal_static_Result_descriptor;
            }

            @Override
            public Result getDefaultInstanceForType() {
                return Result.getDefaultInstance();
            }

            @Override
            public Result build() {
                Result result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public Result buildPartial() {
                Result result = new Result(this);
                if (bitField0_ != 0) {
                    buildPartial0(result);
                }
                onBuilt();
                return result;
            }

            private void buildPartial0(Result result) {
                int from_bitField0_ = bitField0_;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.code_ = code_;
                }
                if (((from_bitField0_ & 0x00000002) != 0)) {
                    result.success_ = success_;
                }
                if (((from_bitField0_ & 0x00000004) != 0)) {
                    result.message_ = message_;
                }
                if (((from_bitField0_ & 0x00000008) != 0)) {
                    result.data_ = data_;
                }
            }

            @Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof Result) {
                    return mergeFrom((Result) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(Result other) {
                if (other == Result.getDefaultInstance()) return this;
                if (!other.getCode().isEmpty()) {
                    code_ = other.code_;
                    bitField0_ |= 0x00000001;
                    onChanged();
                }
                if (other.getSuccess() != false) {
                    setSuccess(other.getSuccess());
                }
                if (!other.getMessage().isEmpty()) {
                    message_ = other.message_;
                    bitField0_ |= 0x00000004;
                    onChanged();
                }
                if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
                    setData(other.getData());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                onChanged();
                return this;
            }

            @Override
            public final boolean isInitialized() {
                return true;
            }

            @Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                if (extensionRegistry == null) {
                    throw new NullPointerException();
                }
                try {
                    boolean done = false;
                    while (!done) {
                        int tag = input.readTag();
                        switch (tag) {
                            case 0:
                                done = true;
                                break;
                            case 10: {
                                code_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000001;
                                break;
                            } // case 10
                            case 16: {
                                success_ = input.readBool();
                                bitField0_ |= 0x00000002;
                                break;
                            } // case 16
                            case 26: {
                                message_ = input.readStringRequireUtf8();
                                bitField0_ |= 0x00000004;
                                break;
                            } // case 26
                            case 34: {
                                data_ = input.readBytes();
                                bitField0_ |= 0x00000008;
                                break;
                            } // case 34
                            default: {
                                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                    done = true; // was an endgroup tag
                                }
                                break;
                            } // default:
                        } // switch (tag)
                    } // while (!done)
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.unwrapIOException();
                } finally {
                    onChanged();
                } // finally
                return this;
            }

            private int bitField0_;

            private Object code_ = "";

            /**
             * <code>string code = 1;</code>
             *
             * @return The code.
             */
            public String getCode() {
                Object ref = code_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    code_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>string code = 1;</code>
             *
             * @return The bytes for code.
             */
            public com.google.protobuf.ByteString
            getCodeBytes() {
                Object ref = code_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    code_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string code = 1;</code>
             *
             * @param value The code to set.
             * @return This builder for chaining.
             */
            public Builder setCode(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                code_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            /**
             * <code>string code = 1;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearCode() {
                code_ = getDefaultInstance().getCode();
                bitField0_ = (bitField0_ & ~0x00000001);
                onChanged();
                return this;
            }

            /**
             * <code>string code = 1;</code>
             *
             * @param value The bytes for code to set.
             * @return This builder for chaining.
             */
            public Builder setCodeBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                code_ = value;
                bitField0_ |= 0x00000001;
                onChanged();
                return this;
            }

            private boolean success_;

            /**
             * <code>bool success = 2;</code>
             *
             * @return The success.
             */
            @Override
            public boolean getSuccess() {
                return success_;
            }

            /**
             * <code>bool success = 2;</code>
             *
             * @param value The success to set.
             * @return This builder for chaining.
             */
            public Builder setSuccess(boolean value) {

                success_ = value;
                bitField0_ |= 0x00000002;
                onChanged();
                return this;
            }

            /**
             * <code>bool success = 2;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearSuccess() {
                bitField0_ = (bitField0_ & ~0x00000002);
                success_ = false;
                onChanged();
                return this;
            }

            private Object message_ = "";

            /**
             * <code>string message = 3;</code>
             *
             * @return The message.
             */
            public String getMessage() {
                Object ref = message_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    message_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>string message = 3;</code>
             *
             * @return The bytes for message.
             */
            public com.google.protobuf.ByteString
            getMessageBytes() {
                Object ref = message_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    message_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string message = 3;</code>
             *
             * @param value The message to set.
             * @return This builder for chaining.
             */
            public Builder setMessage(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                message_ = value;
                bitField0_ |= 0x00000004;
                onChanged();
                return this;
            }

            /**
             * <code>string message = 3;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearMessage() {
                message_ = getDefaultInstance().getMessage();
                bitField0_ = (bitField0_ & ~0x00000004);
                onChanged();
                return this;
            }

            /**
             * <code>string message = 3;</code>
             *
             * @param value The bytes for message to set.
             * @return This builder for chaining.
             */
            public Builder setMessageBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);
                message_ = value;
                bitField0_ |= 0x00000004;
                onChanged();
                return this;
            }

            private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;

            /**
             * <code>bytes data = 4;</code>
             *
             * @return The data.
             */
            @Override
            public com.google.protobuf.ByteString getData() {
                return data_;
            }

            /**
             * <code>bytes data = 4;</code>
             *
             * @param value The data to set.
             * @return This builder for chaining.
             */
            public Builder setData(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                data_ = value;
                bitField0_ |= 0x00000008;
                onChanged();
                return this;
            }

            /**
             * <code>bytes data = 4;</code>
             *
             * @return This builder for chaining.
             */
            public Builder clearData() {
                bitField0_ = (bitField0_ & ~0x00000008);
                data_ = getDefaultInstance().getData();
                onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:Result)
        }

        // @@protoc_insertion_point(class_scope:Result)
        private static final Result DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new Result();
        }

        public static Result getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        private static final com.google.protobuf.Parser<Result>
                PARSER = new com.google.protobuf.AbstractParser<Result>() {
            @Override
            public Result parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                Builder builder = newBuilder();
                try {
                    builder.mergeFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    throw e.setUnfinishedMessage(builder.buildPartial());
                } catch (com.google.protobuf.UninitializedMessageException e) {
                    throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
                } catch (java.io.IOException e) {
                    throw new com.google.protobuf.InvalidProtocolBufferException(e)
                            .setUnfinishedMessage(builder.buildPartial());
                }
                return builder.buildPartial();
            }
        };

        public static com.google.protobuf.Parser<Result> parser() {
            return PARSER;
        }

        @Override
        public com.google.protobuf.Parser<Result> getParserForType() {
            return PARSER;
        }

        @Override
        public Result getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

    }

    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_Result_descriptor;
    private static final
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_Result_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\017RpcResult.proto\"F\n\006Result\022\014\n\004code\030\001 \001(" +
                        "\t\022\017\n\007success\030\002 \001(\010\022\017\n\007message\030\003 \001(\t\022\014\n\004d" +
                        "ata\030\004 \001(\014B$\n\027com.skiff.protobuf.coreB\tRp" +
                        "cResultb\006proto3"
        };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        });
        internal_static_Result_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_Result_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                internal_static_Result_descriptor,
                new String[]{"Code", "Success", "Message", "Data",});
        descriptor.resolveAllFeaturesImmutable();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
