spring:
  cloud:
    gateway:
      discovery:
        locator:
          #开启从注册中心动态创建路由的功能，利用微服务名进行路由
          enabled: false
logging:
  level:
    com.skiff: debug

skiff:
  transfer:
    enabled: true