spring:
  cloud:
    gateway:
      discovery:
        locator:
          #开启从注册中心动态创建路由的功能，利用微服务名进行路由
          enabled: false
skiff:
  gateway:
    request:
      enabled: true
      urls:
        - /api/test/result/getResultRequest
    response:
      enabled: true
      urls:
        - /api/test/result/getResultRequest
        - /api/test/result/getResultRequest2
logging:
  level:
    com.skiff: debug
