spring:
  cloud:
    gateway:
      routes:
        - id: baidu
          uri: https://www.baidu.com
          predicates:
            - Path=/api/baidu/**
          filters:
            - StripPrefix=2
