server:
  port: 8085
spring:
  application:
    name: registry-client




#skiff:
#  registry:
#    client:
#      service-name: ${spring.application.name}
#      ip: 127.0.0.1
#      port: 50052
#    registry:
#      ip: 127.0.0.1
#      port: 50050

logging:
  level:
    com.skiff: debug
