// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: MessageService.proto
// Protobuf Java Version: 4.28.2

package com.skiff.protobuf.rpc;

public final class MessageGrpcService {
  private MessageGrpcService() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      MessageGrpcService.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024MessageService.proto\022\026com.skiff.protob" +
      "uf.rpc\032\rMessage.proto\032\017RpcResult.proto2;" +
      "\n\016MessageService\022)\n\013SendMessage\022\017.Messag" +
      "eRequest\032\007.Result\"\000B\024B\022MessageGrpcServic" +
      "eb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.skiff.protobuf.entity.Message.getDescriptor(),
          com.skiff.protobuf.result.RpcResult.getDescriptor(),
        });
    descriptor.resolveAllFeaturesImmutable();
    com.skiff.protobuf.entity.Message.getDescriptor();
    com.skiff.protobuf.result.RpcResult.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
